services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app

  chainlit:
    build: .
    ports:
      - "8001:8000"
    command: chainlit run chainlit_app/app.py -w
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - backend